clc
clear all
close all
datadir = 'F:\matlab_allcodes_delete\matlab\bin\projectdeep\codes\codes\cifar100_run\Run_CIFAR_10\45degree'; 
downloadCIFAR10Data(datadir);
[XTrain1,YTrain1,XValidation1,YValidation1] = loadCIFAR10Data(datadir);
[XTrain, YTrain] = supervised8(XTrain1);
[XValidation,YValidation] = supervised8(XValidation1);
YTrain= categorical(YTrain);
YValidation= categorical(YValidation);
imageSize = [32 32 3];
pixelRange = [-4 4];
imageAugmenter = imageDataAugmenter( ...
    'RandXReflection',true, ...
    'RandXTranslation',pixelRange, ...
    'RandYTranslation',pixelRange);
augimdsTrain = augmentedImageDatastore(imageSize,XTrain,YTrain);
   % 'DataAugmentation',imageAugmenter);
numUnits = 9;
netWidth = 16;
lgraph = residualCIFARlgraph(netWidth,numUnits,"standard");
miniBatchSize = 128;
learnRate = 0.1*miniBatchSize/128;
valFrequency = floor(size(XTrain,4)/miniBatchSize);
options = trainingOptions('sgdm', ...
    'InitialLearnRate',learnRate, ...
    'MaxEpochs',70, ...
    'MiniBatchSize',miniBatchSize, ...
    'VerboseFrequency',valFrequency, ...
    'Shuffle','every-epoch', ...
    'Plots','training-progress', ...
    'Verbose',false, ...
    'ValidationData',{XValidation,YValidation}, ...
    'ValidationFrequency',valFrequency, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.1, ...
    'LearnRateDropPeriod',60);
[trainedNet,info] = trainNetwork(augimdsTrain,lgraph,options);
